# Controls when the action will run.
on: 
  # Triggers the workflow on push or pull requests events but only for the develop branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
        env:
          WEBHOOKURL: ${{ secrets.WEBHOOKURL }}
          BOTTOKEN: ${{ secrets.BOTTOKEN }}
          PORT: ${{ secrets.PORT }}
      - run: npm ci
      - run: npm install pm2@latest -g #install pm2 global
      - run: pm2 -V #check pm2 version
      - run: pm2 list #check pm2 list
      #running pm2 in mode cluster and --watch set to auto restart if index.js have changes.
      - run: pm2 start index.js --watch -i max

