# Controls when the action will run.
on: 
  # Triggers the workflow on push or pull requests events but only for the develop branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

    # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync:
    runs-on: self-hosted
    steps:
      - run: git pull origin main
      - run: npm install
    